### ISSUE TITLE
test of analytics throws error on server

### ISSUE THREAD

**Issue by woolfg** [openpodcast/api#102]
when running the test suite the following error is thrown on the server even though all tests are green

```
code: 'ERR_HTTP_HEADERS_SENT'
[1] }
[1] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```

**Comment by mre** [comment]
It's probably because of our middleware.

We're using middleware and call `next()` after sending the response. The middleware function may not try to send a response.

```ts
app.get('/path', (req, res, next) => {
  res.send('Hello, World!');
  next(); // Don't call next after sending a response
});
```

Maybe happens here, which is our error handler? https://github.com/openpodcast/api/blob/d9acef6bbed235bbf95fdee0c823bbaf356c4fb7/src/index.ts#L420

**Comment by woolfg** [comment]
will pop up again if still a problem.
